import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google';
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "AA84 | Road to MVP",
  description: "Generated by create next app",
};

const nunito = DM_Sans({
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.className}>
      <body>
          <Header />
        {children}  
      </body>
    </html>
  );
}
